---
- name: Openshift integration 
  hosts: all
  tasks:
   - name: Create a new namespace
     redhat.openshift.k8s:
       name: msabry
       api_version: v1
       kind: Namespace
       state: present
     delegate_to: localhost
